# Generated by Django 5.0.4 on 2024-05-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.EmailField(blank=True, default="", max_length=254)),
                ("patient", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "music_file",
                    models.FileField(
                        blank=True, null=True, upload_to="mainapp/music/%Y/%m/%d"
                    ),
                ),
                (
                    "type",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
        ),
    ]
