# Generated by Django 5.0.4 on 2024-05-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="music_file",
        ),
        migrations.AddField(
            model_name="music",
            name="music_path",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
